targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: flutter_starter|lib/common/domain/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: flutter_starter|lib/common/domain/schema.graphql
      slang_build_runner:
        options:
          base_locale: en
          string_interpolation: braces